[package]
name = "aws-parameters-and-secrets-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
httpmock = "0.6"
temp-env = "0.3"
